# Generated by Django 5.0.7 on 2025-10-01 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_id', models.CharField(max_length=255, unique=True)),
                ('sheet_list_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(default='Akce', max_length=255)),
                ('description', models.CharField(default='')),
                ('place', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('points', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
            ],
            options={
                'unique_together': {('sheet_id', 'sheet_list_id')},
            },
        ),
        migrations.CreateModel(
            name='ImageToEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.event')),
            ],
        ),
        migrations.CreateModel(
            name='UserToEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.user')),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
