# Generated by Django 5.0.7 on 2025-08-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='points',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
