# Generated by Django 5.0.7 on 2025-10-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sheet_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='sheet_list_id',
            field=models.CharField(max_length=255),
        ),
    ]
