# Generated by Django 5.0.7 on 2025-10-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_alter_event_sheet_id_alter_event_sheet_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=1023),
        ),
    ]
